### ISSUE TITLE
No calls

### ISSUE THREAD

**Issue by testingweb624** [Vince1171/OnePlus3-T-Halium-Prebuild#1]
Any updates for calls feature plzzz .. and Multirom to test side by side. plzzz

**Comment by Vince1171** [comment]
the "call issue" isn't fixable for now as it seems to come from the rootfs(ofono)
but as soon as it's fixed, i'll do an update to notify it

For MultiROM, to be honnest, I've never use it, and it's not on the top of my TODO list
I'll do some search, but I cannot promise anything

**Comment by kiranreddyrebel** [comment]
Congrats for Ver 0.6 updates Sir.

Hoping to get calls to be fixed soon. :)

and does this port supports Dual sim ?  or we need to switch to sim whenever needed ?

**Comment by Vince1171** [comment]
Fixed in v0.10
