### ISSUE TITLE
Add plasma-mobile support

### ISSUE THREAD

**Issue by ghost** [Vince1171/OnePlus3-T-Halium-Prebuild#12]
Hi,
I'm trying to try the image to work but it doesn't seem to boot at all for me. The phone just shows me the splash image instead of giving me any feedback.

rootfs used: https://images.plasma-mobile.org/rootfs/pm-rootfs-20190809-105557.tar.gz
halium version used: v0.6 from this repo
script used: https://github.com/JBBgameich/halium-install

I've also made sure userdata and cache are both formatted as ext4, and I've reflashed boot numerous times. 

AFAIK this phone doesn't have a serial console available over the headphone jack, so I really don't know how to proceed now. Any advice on debugging would be greatly appreciated.

Edit: Ubuntu Touch works just fine.

**Comment by ghost** [comment]
Seems like plasma mobile only supports hybris-boot, not halium-boot. I was able to ssh into the system and this seems to be the main problem.

**Comment by ghost** [comment]
Initially I've used halium-boot and it failed because the system mount points are wrong. Then I was informed that only hybris-boot is supported by Plasma Mobile, so I compiled it and now /system mounts just fine. Now the problem is that I don't have any displays available, and the boot process is always stuck at the splash logo. If you need any further testing in the future, just let me know. I have spare devices that I can erase and flash at all time.

**Comment by TheBluestBird** [comment]
Hey! Hello! I also have a spare device, also wish to make plasma mobile working, and ready for different kind of helping

**Comment by TheBluestBird** [comment]
Happened to install UBports on the device, but cant handle plasma mobile. Could install hybris-recovery and telnet there, but nothing goes further, cant even fines logs that are described in hallium manuals. Switching of lxc didn't work

**Comment by GetAGripGal** [comment]
Hello, any update to this? Would like to get it working on my phone. :)

**Comment by testingweb624** [comment]
Me too looking for plasma.
