### ISSUE TITLE
Battery level displayed is half of the real level

### ISSUE THREAD

**Issue by ghost** [Vince1171/OnePlus3-T-Halium-Prebuild#13]
The device only draws about 0.4A no matter what charger I use, and this is not sufficient to charge the battery in a timely manner. I think this is a halium related issue since not even the offline charging mode works.

**Comment by ghost** [comment]
Update: I've went into recovery and the battery is clearly charged at 100%. Rebooted into Ubuntu Touch and the battery percentage is still stuck at 50%.

**Comment by Vince1171** [comment]
yes it's a gui bug. The battery level displayed is half of the real level.
It's a common error on most of the device with qcom hardware.
I cannot fix it as it come from the rootfs.

**Comment by ghost** [comment]
Alright then, thanks for the explanation. If this is isn't a halium related bug, I think we should close this issue for now.
