### ISSUE TITLE
Charging/battery indicator inaccurate (Oneplus 3t)  

### ISSUE THREAD

**Issue by Stefano0101** [Vince1171/OnePlus3-T-Halium-Prebuild#16]
Charging indicator on Op3t is inaccurate, only reporting 50% charge level on fully charged phone.

I have let the phone to charge fully and checked the % in TWRP recovery. Upon rebooting to UT, system reporting only 50%. But it will charge in UT, just will show wrong percentage.

**Comment by Vince1171** [comment]
same as #13 
it a common error to all halium ports with qcom devices

**Comment by Stefano0101** [comment]
So we can close this one for now.

**Comment by Vince1171** [comment]
lets it open
so there'll not be futher duplicate ^^

**Comment by Stefano0101** [comment]
Ok then

**Comment by Vince1171** [comment]
Fixed
https://github.com/ubports/indicator-power/pull/19
