### ISSUE TITLE
error log,how to install?

### ISSUE THREAD

**Issue by xtod** [Vince1171/OnePlus3-T-Halium-Prebuild#19]
root@zb14:~# ./halium-install-standalone.sh -p ut ubports.tar.gz system.img 
Debug: Chosen rootfs is ubports.tar.gz
Debug: Chosen android image is system.img
Debug: Chosen release is ut

I: Writing rootfs into mountable image
I: Writing android image into mountable image
I: Running post installation tasks
enabling Mir ... [done]
enabling SSH ... [done]
Please enter a new password for the user 'phablet':
chroot: failed to run command ‘passwd’: Exec format error
Failed, please try again
chroot: failed to run command ‘passwd’: Exec format error

**Comment by Vince1171** [comment]
have you installed the depedencies of halium-script?

**Comment by xtod** [comment]
Follow the prompts already installed, I changed the computer and installed successfully.
