### ISSUE TITLE
我想刷入

### ISSUE THREAD

**Issue by hu19960925** [Vince1171/OnePlus3-T-Halium-Prebuild#2]
但是不知道怎么刷，写入boot system镜像后无法启动。不知道怎么刷入压缩文件.gz。刷入后如何启动到ubuntu touch？我是热爱者，但是我是小白。

**Comment by Vince1171** [comment]
Hi 
Unfortunately I don't understand Chinese :-/
can you translate your message in English please?
I'll be glad to help you then :D

**Comment by godspirit00** [comment]
> Hi
> Unfortunately I don't understand Chinese :-/
> can you translate your message in English please?
> I'll be glad to help you then :D

Let me translate it for you.
The guy said, 

>  I would very much like to flash it, but I don't know how to do it. It doesn't boot after writing boot, system images. I don't know how to flash .gz files either. How to boot into UT after flashing? Newbie here.

Sorry the translation may be a bit late :-P


To @hu19960925：

> 但是不知道怎么刷，写入boot system镜像后无法启动。不知道怎么刷入压缩文件.gz。刷入后如何启动到ubuntu touch？我是热爱者，但是我是小白。

readme.md 里有提到怎么刷，仔细看看呗

**Comment by Vince1171** [comment]
@godspirit00 thanks for the help :)
