### ISSUE TITLE
Calls not working

### ISSUE THREAD

**Issue by jussihi** [Vince1171/OnePlus3-T-Halium-Prebuild#21]
Hello, 

in the newest release (1.0) it seems like I can't make/receive calls at all. So the regression is not only for receiving calls, but instead also making calls I cannot hear anything.

I'm using the edge rootfs.

**Comment by Vince1171** [comment]
calls should work now, thanks to Marius :)
be aware that you can now install UT on op3 via the [installer](github.com/ubports/ubports-installer) (but only arm64 for now)
