### ISSUE TITLE
webapp container not working due to problem with Mir, "Mir returned: "Failed to connect: not accepted by server""

### ISSUE THREAD

**Issue by GetAGripGal** [Vince1171/OnePlus3-T-Halium-Prebuild#22]
Any webapp i installl will not boot up, whenever i run the webapp-container command in the terminal i get: "Mir returned: "Failed to connect: not accepted by server"".

I am thinking this might be an issue with halium/apparmor. (if not i apologize for posting it here)

**Comment by testingweb624** [comment]
Try ubport from ubport.com. Vince and Marius has official port in official
site. Try that.
