### ISSUE TITLE
mka systemimage error

### ISSUE THREAD

**Issue by cheshirean** [Vince1171/OnePlus3-T-Halium-Prebuild#23]
Hello!
I tried to assemble the image following the instructions from the readme. As a result mka systemimage:
`ninja: error: 'vendor/oneplus/oneplus3/proprietary/lib/libloc_api_v02.so', needed by '/home/user/halium-vince/out/target/product/oneplus3/obj_arm/SHARED_LIBRARIES/libloc_api_v02_intermediates/LINKED/libloc_api_v02.so', missing and no known rule to make it
`

**Comment by Vince1171** [comment]
this error occurs if you're using the [Muppets vendor repo](https://github.com/TheMuppets/proprietary_vendor_oneplus/) instead of [mine](https://github.com/Vince1171/proprietary_vendor_oneplus/)

**Comment by cheshirean** [comment]
This helped, but these are not all the problems that I encountered while building the "systemimage".
After changing the manifest and getting the correct source, we have this error:
`Lex: libsepol_32 <= external/selinux/libsepol/cil/src/cil_lexer.l
FAILED: /bin/bash -c "prebuilts/misc/linux-x86/flex/flex-2.5.39 -o/home/vadikas/oneplus3-astra/out/host/linux-x86/obj32/SHARED_LIBRARIES/libsepol_intermediates/cil/src/cil_lexer.c external/selinux/libsepol/cil/src/cil_lexer.l"
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)`
A simple way to get rid of it:
`LANG=C mka systemimage`
After that, another error is issued:
`error: ro.build.fingerprint cannot exceed 91 bytes: OnePlus/halium_oneplus3/oneplus3:7.1.1/NOF27B/eng.vadika.20200205.134920:userdebug/test-keys (92)`
A simple way to fix it:
`LANG=C mka systemimage BUILD_FINGERPRINT="....."`
Building host system is Ubuntu 18.04, with all the latest updates.

**Comment by Vince1171** [comment]
The fingerprints error is new
I never see it O_o

**Comment by cheshirean** [comment]
I also have not encountered her before. When building project in July-August 2019, also on Ubuntu 18.04, this error was not. Also, it was not during then building on a debian based distribution. I can only assume that the matter is still in the Ubuntu.
