### ISSUE TITLE
breakfast fails

### ISSUE THREAD

**Issue by BEa45xz** [Vince1171/OnePlus3-T-Halium-Prebuild#3]
i just tried my hands on halium and i am getting this error as i run breakfast. 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/49711174/56269827-e7dfc780-60f4-11e9-89cd-99ffd0a9a1db.png">

i have read what roomservice does and manually backtracked why the error occurs and it seems there is no 'revision' object found inside the element object
atleast i get "none" returned. 

i set up the manifest file as the documentation laid out and also manually i am not able to find any indication for a "revision" section. my device is the oneplus3t and the basis for resulting manifest is to be found here https://github.com/Halium/halium-devices/blob/halium-7.1/manifests/oneplus_oneplus3.xml

**Comment by BEa45xz** [comment]
to describe it a little better. the one element that contains "default" (as requested by the roomservice.py script) has no revision key in it.

the element retrieved is:
´´´
default remote="aosp"
  sync-j=8
  sync-c=true. 
´´´

**Comment by BEa45xz** [comment]
this is what it think happens:
- breakfast uses roomservice.py which hasnt any local reference and starts looking for a definition for lineageos. which isnt in default.

so put it in manually, resulted in:
´´´
default remote="aosp"
sync-j=8
sync-c=true
revision="cm-14.1"
´´´



this fails with this error:
https://pasteboard.co/IaGxwKa.png

i think breakfast now tries to access github as a source for env variables it is setting up
this error i evade by manually adding github to the manifest.xml
like this:
´´´
remote name="github" fetch="https://github.com"
´´´



this on otherhand results in another error:
https://pasteboard.co/IaGDtEa.png

it claims there is a duplicate path in the manifest.xml but the path 
´device/oneplus/oneplus3´ doesnt even appear in the file at all.

from here i dont even know

**Comment by BEa45xz** [comment]
i also tried to change 
´´´
default remote="aosp"
´´´

into 
´´´
default remote="los"
´´´

with the same parameters, just as ´los´ has.

as expected the outcome does not change.

**Comment by BEa45xz** [comment]
okay it worked now:

i did this...

I changed every source from halium ("hal") to lineageos ("los") and adjusted the links.
additionally i added the revision key,value pair with corresponding branch "cm-14.1"

can you please update the xml file so it works out of the box?
thanks to the user posting his commands in the comment section before. so i had a reference.

heres the content of the hopefully future xml. (not everyone should need to learn the build system to start hacking on the software, it prevents people from actually getting into it and me from getting possible future updates on before mentioned.)

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project path="device/oneplus/oneplus3" name="android_device_oneplus_oneplus3" remote="los" revision="cm-14.1" />
    <project path="device/oppo/common" name="android_device_oppo_common" remote="los" revision="cm-14.1" />

    <project path="vendor/oneplus" name="proprietary_vendor_oneplus" remote="them" />

    <project path="kernel/oneplus/msm8996" name="android_kernel_oneplus_msm8996" remote="los" revision="cm-14.1"/>
</manifest>
```

**Comment by Vince1171** [comment]
Personally I don't use breakfast for the Oneplus 3, I use lunch, and then halium_oneplus3_enguser (something like that)
