### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by hu19960925** [Vince1171/OnePlus3-T-Halium-Prebuild#4]
There was no sound in the local test.

**Comment by hu19960925** [comment]
Is there any progress now? It feels superfluous when used in large memory devices. I like this project very much and would like to participate in it, but I will not transplant it.

**Comment by hu19960925** [comment]
Content from Web Translation

**Comment by Vince1171** [comment]
for the sound

**Comment by Vince1171** [comment]
In order to have the sound, you'll have to install the additionnal package 
```wget https://ci.ubports.com/job/pulseaudio-modules-droid/job/PR-1/8/artifact/pulseaudio-modules-droid-24_11.1.76+0~20190225000127.8~1.gbp826b96_armhf.deb --no-check-certificate
dpkg -i pulseaudio-modules-droid-24_11.1.76+0~20190225000127.8~1.gbp826b96_armhf.deb
sed -i -e "s/load-module module-droid-discover voice_virtual_stream=true/load-module module-droid-card-24/" /etc/pulse/touch.pa
```
for progresses, it take time...
